pipeline {
   sh 'git config --global --add safe.directory "$WORKSPACE"'
   stage('Unit Test - Frontend') {
    agent {
        docker {
            image 'node:18'
            reuseNode true
        }
    }
    steps {
        dir('bugtracker-frontend') {
            sh 'npm ci'
            sh 'npm test'
        }
    }
}

}
