pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            agent {
                docker {
                  image 'snakee/golang-junit:1.21'
                  reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                  sh 'go test -v ./...'
                }
            }
        }
        stage('Unit Test - Frontend') {
              agent {
                  docker {
                    image 'node:18'
                    reuseNode true
                  }
              }
            steps {
                dir('bugtracker-frontend') {
                  sh 'npm ci'
                  sh 'npm test'
                }
            }
        }
    }
}
